rabbit:
  hosts:
  vars:
    rabbitmq_cluster_master: "{{ hostvars['localhost']['first_node']['private_dns_name'] }}"
    update_hosts: true
    backup_queues_in_two_nodes: true
    ansible_user: admin
    ansible_become: yes
    ansible_port: 22
    private_key_file: your_path_to_key_file
    # next bunch of values are set from "Set facts" task directives
    first_node_private_dns_name: "{{ hostvars['localhost']['first_node']['private_dns_name'] }}"
    first_node_private_ip_address: "{{ hostvars['localhost']['first_node']['private_ip_address'] }}"
    first_node_instance_id: "{{ hostvars['localhost']['first_node']['id'] }}"
    second_node_private_dns_name: "{{ hostvars['localhost']['second_node']['private_dns_name']  }}"
    second_node_private_ip_address: "{{ hostvars['localhost']['second_node']['private_ip_address'] }}"
    second_node_instance_id: "{{ hostvars['localhost']['second_node']['id'] }}"
    third_node_private_dns_name: "{{ hostvars['localhost']['third_node']['private_dns_name']  }}"
    third_node_private_ip_address: "{{ hostvars['localhost']['third_node']['private_ip_address'] }}"
    third_node_instance_id: "{{ hostvars['localhost']['third_node']['id'] }}"
    rabbitmq_sg_id: "{{ hostvars['localhost']['rabbit_sg']['id'] }}"
