rabbit_local_user: rabbit
rabbit_local_password: your_rabbit_pass
your_key_pair_name: key_pair_name
your_vpc_id: vpc_id
your_aws_account: aws_account
your_aws_profile: aws_profile
your_aws_region: aws_region
your_instance_type: t3a.small
your_node_01_hostname: rabbitmq-node01
your_node_02_hostname: rabbitmq-node02
your_node_03_hostname: rabbitmq-node03
your_private_subnet_id_01: subnet-aaa
your_private_subnet_id_02: subnet-bbb
your_private_subnet_id_03: subnet-ccc
your_public_subnet_id_01: subnet-xxx
your_public_subnet_id_02: subnet-yyy
your_public_subnet_id_03: subnet-zzz
your_lb_security_group: security_group_name
your_environment_value: prod
rabbit_exporter_port: 9419
prometheus_exporter_port: 15692
rabbitmq_tls_port: 5671
rabbitmq_amqp_port: 5672
rabbitmq_epmd_port: 4369
rabbitmq_stream_port_1: 5551
rabbitmq_stream_port_2: 5552
rabbitmq_mqtt_port_1: 1883
rabbitmq_mqtt_port_2: 8883
rabbitmq_node_port: 25672
rabbitmq_mgmt_port: 15672
rabbitmq_http_api_port: 15671
host_key_checking: false
