---
dependencies: []
galaxy_info:
  author: Andrey Strelnikov
  role_name: rabbit_exporter
  description: Prometheus' rabbit_exporter for Linux hosts with RabbitMQ installed.
  company: _
  license: license (MIT)
  min_ansible_version: "2.7"
  platforms:
    - name: EL
      versions:
        - all
    - name: GenericUNIX
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: GenericBSD
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: SLES
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system
    - docker
    - containers
    - monitoring
    - prometheus
    - node
    - exporter
    - metrics
